version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: munzapp-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data:
