# Generated by Django 5.0.1 on 2024-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='issue_at',
            field=models.CharField(verbose_name='Дата выпуска в обращение'),
        ),
    ]
