# Generated by Django 5.0.2 on 2024-02-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coins", "0002_alter_coin_issue_at"),
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Оценка"),
                ),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_reviews",
                        to="coins.coin",
                        verbose_name="Монета",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_reviews",
                        to="guests.guest",
                        verbose_name="Автор обзора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "unique_together": {("guest", "coin")},
            },
        ),
    ]
