# Generated by Django 5.0.2 on 2024-02-15 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        unique=True,
                        verbose_name="Токен",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Гость",
                "verbose_name_plural": "Гости",
            },
        ),
    ]
